name: FlexiML_py Build & Test

on:
  push:
  pull_request:

jobs:
  python_tests:
    name: FlexiML - Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install initial requirements
        run: pip install "maturin>=1.4,<=2.0" pytest==8.3.2
      - name: Build and Install FlexiML
        run: |
          maturin build
          pip install target/wheels/*.whl
      - name: Run Python Tests
        run: pytest
